### ISSUE TITLE
Possible plagiarism? EDIT: nope, all good

### ISSUE THREAD

**Issue by pawamoy** [evildmp/diataxis-documentation-framework#136]
Hi, I stumbled upon this: https://docs.divio.com/documentation-system/. Isn't it exactly the diataxis framework? I don't see it mentioned anywhere. It even reuses the same images...

**Comment by pawamoy** [comment]
Unless... it's the same author behind both ^^? Is evildmp Daniele Procida? Sorry, on mobile, can't use sound to watch the video in divio's docs so my investigation is quite poor. I just find this confusing for now :)

**Comment by pawamoy** [comment]
Yes OK, evildmp is Daniele. Sorry for the noise.   I suppose Divio's docs could be updated now that the documentation framework was extracted into "Diataxis" ^^? Anyway, closing, feel free to act as you see fit! And thanks for the great project!

**Comment by agilgur5** [comment]
For reference, the author has clarified the relationship between Divio and Diataxis themselves in https://github.com/evildmp/diataxis-documentation-framework/issues/14#issuecomment-1170838014 and https://github.com/evildmp/diataxis-documentation-framework/issues/43#issuecomment-1017745749
