### ISSUE TITLE
Translation 

### ISSUE THREAD

**Issue by seupedro** [evildmp/diataxis-documentation-framework#28]
Hi! 
First of all, thanks for this brilliant work. 👏

It summarizes what I have been struggling for years to convince my fellow coworkers  what a documentation should be.

It so valuable to me that I would like to translate it entirely to portuguese. What you think about that? And how we could accomplish it?

**Comment by evildmp** [comment]
I would be really delighted. In order to make it maintainable, we should take an approach outlined at https://docs.readthedocs.io/en/stable/guides/manage-translations.html.

**Comment by seupedro** [comment]
Great!
I have started  the translation. You can check the progress here #29 
I believe I can finish the translation in two weeks or less. 

See ya!
