### ISSUE TITLE
Duplicate words

### ISSUE THREAD

**Issue by CynthiaPeter** [evildmp/diataxis-documentation-framework#39]
Under 'Explanations', the subtopic "Talk about the subject" has a sentence with duplicate words. 

"you should should be able to place an implicit (or even explicit) about in front of each title"

I wish to make an edit and send in a PR if it's ok?
![image](https://user-images.githubusercontent.com/33583060/122912514-52819300-d350-11eb-87c8-83307ed69ca5.png)

**Comment by CynthiaPeter** [comment]
I worked on this already.

**Comment by agilgur5** [comment]
> I worked on this already.

For posterity, this was resolved by #40
