### ISSUE TITLE
What is the actual name?

### ISSUE THREAD

**Issue by TRSx80** [evildmp/diataxis-documentation-framework#43]
Diataxis, I guess?

FWIW, I followed a link originally to [the page at Divio](https://documentation.divio.com/) which is titled "The Documentation System."

Then there is this quote (both here and there): "The Grand Unified Theory of Documentation" from David Laing.  I did a little searching on the Internet, but could not suss out that reference.

Anyway, perhaps a little clarification might be in order?

These are great ideas that I would like to help spread, ideally with the correct name though.  :smile:

**Comment by evildmp** [comment]
[I created the framework while at Divio](https://diataxis.fr/development/), but have since continued to develop it.

**Comment by TRSx80** [comment]
> The front page has this comment about "The Grand Unified Theory of Documentation" from David Laing. What does that mean?

I was wondering about that, too.  I even searched around Internet (as mentioned in OP) to no avail.

**Comment by brandondavid** [comment]
> > The front page has this comment about "The Grand Unified Theory of Documentation" from David Laing. What does that mean?
> 
> I was wondering about that, too. I even searched around Internet (as mentioned in OP) to no avail.
> It would be wonderful if a sentence of two could be added to README / Intro (or wherever) explaining that a bit.


I believe it's a reference to [https://twitter.com/davidklaing/status/1278130377228337154](https://twitter.com/davidklaing/status/1278130377228337154)
